services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      # map đúng tên biến mà image mongo cần:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME} # tên user app (không phải root)
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD} # password user app
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT:-4000}
      # Kết nối bằng app user (không phải root):
      MONGODB_URI: mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=${MONGO_DB_NAME}
      CORS_ORIGIN: ${CORS_ORIGIN}
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    expose: ["${BACKEND_PORT}"]

  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_BASE: /api
    depends_on: [backend]
    ports:
      - "${HTTP_PORT:-8080}:80"

volumes:
  mongo_data:
